name: Tests

on:
  push:
  pull_request:

jobs:
  tests:
    name: PHP ${{ matrix.php }}; PHPUnit ${{ matrix.phpunit }}
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        php: ['7.4', '8.0', '8.1', '8.2', '8.3', '8.4', '8.5']
        phpunit: ['9.6', '10.5', '11.5', '12.5']
        exclude:
          - php: '7.4'
            phpunit: '10.5'
          - php: '7.4'
            phpunit: '11.5'
          - php: '7.4'
            phpunit: '12.5'
          - php: '8.0'
            phpunit: '10.5'
          - php: '8.0'
            phpunit: '11.5'
          - php: '8.0'
            phpunit: '12.5'
          - php: '8.1'
            phpunit: '11.5'
          - php: '8.1'
            phpunit: '12.5'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: none
        env:
          update: true

      - name: Setup Problem Matchers
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"


      - name: Setup Analyzer v4
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer require "graham-campbell/analyzer:^4.2" --no-update --no-interaction
        if: ${{ matrix.phpunit == '9.5' || matrix.phpunit == '9.6' || matrix.phpunit == '10.1' || matrix.phpunit == '10.5' }}

      - name: Setup Analyzer v5
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer require "graham-campbell/analyzer:^5.0" --no-update --no-interaction
        if: ${{ matrix.phpunit == '11.0' || matrix.phpunit == '11.5' }}

      - name: Setup PHPUnit
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer require "phpunit/phpunit:${{ matrix.phpunit }}.*" --no-update --no-interaction

      - name: Install PHP Dependencies
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer update --no-interaction --no-progress

      - name: Execute PHPUnit
        run: vendor/bin/phpunit
